
version: '3'

services:

  grid2svr:
    container_name: grid2svr
    image: mongo
    command: mongod --shardsvr --replSet grid2rs --port 27017 --dbpath /data/db
    ports:
      - 50004:27017
    volumes:
      - grid2svr:/data/db

volumes:
  grid2svr: {}